#!/bin/bash

# Update package lists
sudo apt-get update

# Install Apache Web Server
sudo apt-get install -y apache2

# Install PHP and some commonly used extensions
sudo apt-get install -y php libapache2-mod-php php-mysql php-cli php-fpm php-json php-common php-mbstring php-zip php-gd php-xml php-curl php-pear

# Optionally, install Composer, PHP's dependency manager
cd /tmp
curl -sS https://getcomposer.org/installer -o composer-setup.php
sudo php composer-setup.php --install-dir=/usr/local/bin --filename=composer
