#!/bin/bash

# Start the Apache Web Server
sudo systemctl start httpd

# If you're using php-fpm:
# sudo systemctl start php-fpm

# Ensure Apache is set to start on boot
sudo systemctl enable httpd

# If using php-fpm, also ensure it starts on boot:
# sudo systemctl enable php-fpm
